services:
  api:
    build:
      context: .
    container_name: portal-chat-api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
