services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #use .env to load environment variables
        - PUBLIC_URL=${PUBLIC_URL}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - OPENAI_ORG_ID=${OPENAI_ORG_ID}
          #MONGO DB SETTINGS ========================================
        - PCAPI_MONGO_DB=${PCAPI_MONGO_DB}
        - PCAPI_MONGO_COLLECTION_USER=${PCAPI_MONGO_COLLECTION_USER}
        - PCAPI_MONGO_COLLECTION_LOGS=${PCAPI_MONGO_COLLECTION_LOGS}
        - PCAPI_MONGO_URL=${PCAPI_MONGO_URL}
          #===========================================================
        - LISTENER_AUTH_KEY=${LISTENER_AUTH_KEY}
        - PINECONE_API_KEY=${PINECONE_API_KEY}
        - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
        - PINECONE_INDEX_MASTER=${PINECONE_INDEX_MASTER}
        - PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS=${PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS}
        - PORT=${PORT}
        - PORTAL_CHAT_API_KEY=${PORTAL_CHAT_API_KEY}
        - PYTHONDONTWRITEBYTECODE=1
        # NGROK SETTINGS ============================================
        - NGROK_TUNNEL_PORT=${NGROK_TUNNEL_PORT}
        - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
        #========================================================
        - DISCORD_APP_AUTH_TOKEN=${DISCORD_APP_AUTH_TOKEN}
        - DISCORD_APP_ID=${DISCORD_APP_ID}
        - DISCORD_APP_INTENTS=${DISCORD_APP_INTENTS}
        - DISCORD_APP_PUBLIC_KEY=${DISCORD_APP_PUBLIC_KEY}
        - DISCORD_BOT_APP_INVITE_LINK=${DISCORD_BOT_APP_INVITE_LINK}

    container_name: portal-chat-api
    environment:
      PUBLIC_URL: ${PUBLIC_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID}
      PCAPI_MONGO_DB: ${PCAPI_MONGO_DB}
      PCAPI_MONGO_COLLECTION_USER: ${PCAPI_MONGO_COLLECTION_USER}
      PCAPI_MONGO_COLLECTION_LOGS: ${PCAPI_MONGO_COLLECTION_LOGS}
      PCAPI_MONGO_URL: ${PCAPI_MONGO_URL}
      LISTENER_AUTH_KEY: ${LISTENER_AUTH_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
      PINECONE_INDEX_MASTER: ${PINECONE_INDEX_MASTER}
      PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS: ${PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS}
      PORT: ${PORT}
      PORTAL_CHAT_API_KEY: ${PORTAL_CHAT_API_KEY}
      PYTHONDONTWRITEBYTECODE: 1
      NGROK_TUNNEL_PORT: ${NGROK_TUNNEL_PORT}
      NGROK_AUTH_TOKEN: ${NGROK_AUTH_TOKEN}
      DISCORD_APP_AUTH_TOKEN: ${DISCORD_APP_AUTH_TOKEN}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_APP_INTENTS: ${DISCORD_APP_INTENTS}
      DISCORD_APP_PUBLIC_KEY: ${DISCORD_APP_PUBLIC_KEY}
      DISCORD_BOT_APP_INVITE_LINK: ${DISCORD_BOT_APP_INVITE_LINK}
    expose:
      - ${PORT}
      - ${NGROK_TUNNEL_PORT}
    ports:
      - "${PORT}:${PORT}"
      - "${NGROK_TUNNEL_PORT}:${NGROK_TUNNEL_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
