FROM tiangolo/uvicorn-gunicorn:python3.10-slim

ARG CHAT_SERVICE_URL="http://0.0.0.0:8000"
ARG OPENAI_API_KEY=""
ARG OPENAI_ORG_ID=""
ARG PINECONE_API_KEY=""
ARG PINECONE_ENVIRONMENT="dev"
ARG PINECONE_INDEX_MASTER=""
ARG PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS="game-systems"
ARG PORT=8000
ARG HOST="http://0.0.0.0"
ARG PORTAL_CHAT_API_KEY="internal api key"
ARG MONGO_CHAT_API_SETTINGS="{'MDB_DATABASE':'portal-chat-api', 'MDB_USERS_COLLECTION':'users', 'MDB_LOGS_COLLECTION':'logs'}"
ARG MONGO_URL="mongodb://mongo:auth@host:port"
ARG LISTENER_AUTH_KEY="internal api key"


LABEL key="portal-chat-api"

COPY requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /tmp/requirements.txt && \
    apt-get update && apt-get install -y git
    
EXPOSE ${PORT}

ENV CHAT_SERVICE_URL=${CHAT_SERVICE_URL}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV OPENAI_ORG_ID=${OPENAI_ORG_ID}
ENV PINECONE_API_KEY=${PINECONE_API_KEY}
ENV PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
ENV PINECONE_INDEX_MASTER=${PINECONE_INDEX_MASTER}
ENV PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS=${PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS}
ENV PORT=${PORT}
ENV PORTAL_CHAT_API_KEY=${PORTAL_CHAT_API_KEY}
ENV MONGO_CHAT_API_SETTINGS=${MONGO_CHAT_API_SETTINGS}
ENV MONGO_URL=${MONGO_URL}
ENV LISTENER_AUTH_KEY=${LISTENER_AUTH_KEY}

COPY ./app /app



