FROM tiangolo/uvicorn-gunicorn:python3.11

ARG CHAT_SERVICE_URL="http://0.0.0.0:8000"
ARG OPENAI_API_KEY=""
ARG OPENAI_ORG_ID=""
ARG PINECONE_API_KEY=""
ARG PINECONE_ENVIRONMENT="dev"
ARG PINECONE_INDEX_MASTER=""
ARG PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS="game-systems"
ARG PORT=8000

LABEL key="portal-chat-api"

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

EXPOSE ${PORT}

ENV CHAT_SERVICE_URL=${CHAT_SERVICE_URL}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV OPENAI_ORG_ID=${OPENAI_ORG_ID}
ENV PINECONE_API_KEY=${PINECONE_API_KEY}
ENV PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
ENV PINECONE_INDEX_MASTER=${PINECONE_INDEX_MASTER}
ENV PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS=${PINECONE_INDEX_NAMESPACE_GAME_SYSTEMS}
ENV PORT=${PORT}

COPY ./app /app